Update Ubuntu version to 20.04 LTS/Focal
Aurorastation/dm-buildimage pull request #2
Opened 2021-03-12 20:15 UTC by MarinaGryphon

Potential fix for icon cache errors?

2021-03-13 19:13 UTC, Arrow768 approved these changes

2021-03-13 19:19 UTC, Arrow768 requested changes
Actually that should have been a changes requested.
This fails during the docker build with:
```
Errors were encountered while processing:
/var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_i386.deb
```

2021-05-05 00:36 UTC, MarinaGryphon commented on Dockerfile
> +FROM i386/ubuntu:focal
```suggestion
FROM i386/ubuntu:focal
```

2021-05-05 00:36 UTC, MarinaGryphon commented on Dockerfile
> +FROM i386/ubuntu:focal.
```suggestion
FROM i386/ubuntu:focal
```

2021-05-05 00:56 UTC, MarinaGryphon commented on Dockerfile
> +FROM i386/ubuntu:focal
```suggestion
FROM i386/ubuntu:groovy
```

2021-05-05 00:56 UTC, MarinaGryphon commented on Dockerfile
> +FROM i386/ubuntu:groovy
```suggestion
FROM i386/ubuntu:hirsute
```

2021-05-05 00:58 UTC, MarinaGryphon commented on Dockerfile
> +FROM i386/ubuntu:hirsute
```suggestion
FROM i386/ubuntu2:hirsute
```

2021-05-05 01:03 UTC, MarinaGryphon commented on Dockerfile
> +FROM i386/ubuntu2:hirsute
```suggestion
FROM amd64/ubuntu:bionic
```

2021-05-05 01:44 UTC, MarinaGryphon commented on Dockerfile
> +FROM amd64/ubuntu:bionic
```suggestion
FROM amd64/ubuntu:groovy
```

2021-05-05 02:00 UTC, MarinaGryphon commented on Dockerfile
> +    && apt-get install -y libstdc++6:i386 gcc-multilib g++-7 g++-7-multilib libssl1.1:i386 zlib1g:i386
```suggestion
    && apt-get install -y libstdc++6:i386 gcc-multilib g++-7 g++-7-multilib libssl1.1:i386 zlib1g:i386 \
```

2021-05-05 02:41 UTC, closed without merging